export const DATA_home = {
  campanhas: [
    {
      id: 1,
      imagem: 'https://via.placeholder.com/480x248',
      hashtag: 'Campanha #01',
      title: 'Como melhorar a rastreabilidade da cadeia?',
      link: '/campaign/detailed-campaign',
      criar_ideia: true,
    },
    {
      id: 2,
      imagem: 'https://via.placeholder.com/480x248',
      hashtag: 'Campanha #06',
      title: 'Como aumentar a produtividade no processo de despacho?',
      link: '/campaign/detailed-campaign',
      criar_ideia: true,
    },
    {
      id: 3,
      imagem: 'https://via.placeholder.com/480x248',
      hashtag: 'Campanha #03',
      title: 'Quais as oportunidades da robótica nos armazêns?',
      link: '/campaign/detailed-campaign',
      criar_ideia: true,
    },
    {
      id: 4,
      imagem: 'https://via.placeholder.com/480x248',
      hashtag: 'Campanha #01',
      title: 'Como melhorar a rastreabilidade da cadeia?',
      link: '/campaign/detailed-campaign',
      criar_ideia: true,
    },
    {
      id: 5,
      imagem: 'https://via.placeholder.com/480x248',
      hashtag: 'Campanha #01',
      title: 'Como melhorar a rastreabilidade da cadeia?',
      link: '/campaign/detailed-campaign',
      criar_ideia: true,
    },
    {
      id: 6,
      imagem: 'https://via.placeholder.com/480x248',
      hashtag: 'Campanha #01',
      title: 'Como melhorar a rastreabilidade da cadeia?',
      link: '/campaign/detailed-campaign',
      criar_ideia: true,
    },
  ],
  camapnhas_top: [
    {
      id: 1,
      title: 'Como melhorar a rastreabilidade da cadeia?',
      link: '/campaign/detailed-campaign',
      hashtag: 'Campanha #01',
      imagem: 'https://via.placeholder.com/190x100',
      posicao: '1º',
      qnt_ideias: 55,
    },
    {
      id: 2,
      title: 'Como aumentar a produtividade do processo de despacho?',
      link: '/campaign/detailed-campaign',
      hashtag: 'Campanha #08',
      imagem: 'https://via.placeholder.com/190x100',
      posicao: '2º',
      qnt_ideias: 48,
    },
    {
      id: 3,
      title: 'Quais as oportunidades dos veículos elétricos para o negócio?',
      link: '/campaign/detailed-campaign',
      hashtag: 'Campanha #12',
      imagem: 'https://via.placeholder.com/190x100',
      posicao: '3º',
      qnt_ideias: 22,
    },
  ],
  camapnhas_recentes: [
    {
      id: 1,
      title: 'Como melhorar a rastreabilidade da cadeia?',
      link: '/campaign/detailed-campaign',
      hashtag: 'Campanha #01',
      imagem: 'https://via.placeholder.com/190x100',
      posicao: '1º',
    },
    {
      id: 2,
      title: 'Como aumentar os níveis de segurança do operador?',
      link: '/campaign/detailed-campaign',
      hashtag: 'Campanha #08',
      imagem: 'https://via.placeholder.com/190x100',
      posicao: '2º',
    },
    {
      id: 3,
      title: 'Como melhorar o processo de treinamento?',
      link: '/campaign/detailed-campaign',
      hashtag: 'Campanha #12',
      imagem: 'https://via.placeholder.com/190x100',
      posicao: '3º',
    },
  ],
  info_public: [
    {
      id: 1,
      qnt: '02',
      value: 'Ideias criadas',
    },
    {
      id: 2,
      qnt: '02',
      value: 'Projetos em implantação',
    },
  ],
  info_users: [
    {
      imagen: 'https://via.placeholder.com/180x132',
      position: '1º',
      name: 'Jane Cooper',
      qnt_ideals: '12',
      qnt_collaborations: '32',
      id: 1,
    },
    {
      imagen: 'https://via.placeholder.com/180x132',
      position: '2º',
      name: 'Jane Cooper',
      qnt_ideals: '10',
      qnt_collaborations: '27',
      id: 2,
    },
    {
      imagen: 'https://via.placeholder.com/180x132',
      position: '3º',
      name: 'Jane Cooper',
      qnt_ideals: '8',
      qnt_collaborations: '23',
      id: 3,
    },
  ],
  ideas_send: [
    {
      title: 'Adipiscing elit integer enim nulla ',
      position: '#23',
      tag: 'Desafio Atendido',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vulputate diam ut lacus fringilla, eu pharetra lectus rutrum. Donec suscipit aliquet lorem ac maximus...',
      images_users: [
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
      ],
      list_images_users:
        'Leslie Simmons, Wade Warren, Sarah Watson e Devon Lane.',
      id: 1,
    },
    {
      title: 'Adipiscing elit integer enim nulla ',
      position: '#24',
      tag: 'Desafio Atendido',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vulputate diam ut lacus fringilla, eu pharetra lectus rutrum. Donec suscipit aliquet lorem ac maximus...',
      images_users: [
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
      ],
      list_images_users:
        'Leslie Simmons, Wade Warren, Sarah Watson e Devon Lane.',
      id: 2,
    },
    {
      title: 'Adipiscing elit integer enim nulla ',
      position: '#25',
      tag: 'Desafio Atendido',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vulputate diam ut lacus fringilla, eu pharetra lectus rutrum. Donec suscipit aliquet lorem ac maximus...',
      images_users: [
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
      ],
      list_images_users:
        'Leslie Simmons, Wade Warren, Sarah Watson e Devon Lane.',
      id: 3,
    },
    {
      title: 'Adipiscing elit integer enim nulla ',
      position: '#26',
      tag: 'Desafio Atendido',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vulputate diam ut lacus fringilla, eu pharetra lectus rutrum. Donec suscipit aliquet lorem ac maximus...',
      images_users: [
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
      ],
      list_images_users:
        'Leslie Simmons, Wade Warren, Sarah Watson e Devon Lane.',
      id: 4,
    },
    {
      title: 'Adipiscing elit integer enim nulla ',
      position: '#27',
      tag: 'Desafio Atendido',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vulputate diam ut lacus fringilla, eu pharetra lectus rutrum. Donec suscipit aliquet lorem ac maximus...',
      images_users: [
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
      ],
      list_images_users:
        'Leslie Simmons, Wade Warren, Sarah Watson e Devon Lane.',
      id: 5,
    },
    {
      title: 'Adipiscing elit integer enim nulla ',
      position: '#28',
      tag: 'Desafio Atendido',
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vulputate diam ut lacus fringilla, eu pharetra lectus rutrum. Donec suscipit aliquet lorem ac maximus...',
      images_users: [
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
        'https://via.placeholder.com/35x35',
      ],
      list_images_users:
        'Leslie Simmons, Wade Warren, Sarah Watson e Devon Lane.',
      id: 6,
    },
  ],
};
